# Generated by Django 5.1.4 on 2024-12-24 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "body_level",
                    models.CharField(
                        choices=[
                            ("upper", "Upper"),
                            ("lower", "Lower"),
                            ("head", "Head"),
                            ("full-body", "Full-body"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reason", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=150)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=250)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practice_category_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=150)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=250)),
                ("proper_execution", models.TextField()),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practice_subcategory_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="practice.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=150)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=250)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="practice_tag_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Technique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=150)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "body_level",
                    models.CharField(
                        choices=[
                            ("upper", "Upper"),
                            ("lower", "Lower"),
                            ("head", "Head"),
                            ("full-body", "Full-body"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action_types",
                    models.CharField(
                        choices=[
                            ("offense", "Offense"),
                            ("defense", "Defense"),
                            ("offense & defense", "Offense & Defense"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "difficty_level",
                    models.CharField(
                        choices=[
                            ("novice", "Novice"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=50,
                    ),
                ),
                ("steps", models.TextField()),
                ("application", models.CharField(max_length=250)),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="practice.subcategory",
                    ),
                ),
                (
                    "target",
                    models.ManyToManyField(
                        related_name="practice_technique_target_related",
                        to="practice.target",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Combo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=150)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "body_level",
                    models.CharField(
                        choices=[
                            ("upper", "Upper"),
                            ("lower", "Lower"),
                            ("head", "Head"),
                            ("full-body", "Full-body"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action_types",
                    models.CharField(
                        choices=[
                            ("offense", "Offense"),
                            ("defense", "Defense"),
                            ("offense & defense", "Offense & Defense"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "difficty_level",
                    models.CharField(
                        choices=[
                            ("novice", "Novice"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(default="A cool combo!", max_length=250),
                ),
                (
                    "target",
                    models.ManyToManyField(
                        related_name="practice_combot_target", to="practice.target"
                    ),
                ),
                (
                    "technique",
                    models.ManyToManyField(
                        related_name="practice_combo_technique", to="practice.technique"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
