# Generated by Django 5.1.4 on 2025-01-14 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="combo",
            name="body_level",
            field=models.CharField(
                choices=[
                    ("upper-body", "Upper-body"),
                    ("lower-body", "Lower-body"),
                    ("head", "Head"),
                    ("full-body", "Full-body"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="combo",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="target",
            name="body_level",
            field=models.CharField(
                choices=[
                    ("upper-body", "Upper-body"),
                    ("lower-body", "Lower-body"),
                    ("head", "Head"),
                    ("full-body", "Full-body"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="technique",
            name="body_level",
            field=models.CharField(
                choices=[
                    ("upper-body", "Upper-body"),
                    ("lower-body", "Lower-body"),
                    ("head", "Head"),
                    ("full-body", "Full-body"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="texttutorial",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="videotutorial",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="videotutorial",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="tutorials.subcategory",
            ),
        ),
    ]
