# Generated by Django 5.1.5 on 2025-02-05 10:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0002_alter_category_slug_alter_combo_body_level_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="combo",
            old_name="difficty_level",
            new_name="difficulty_level",
        ),
        migrations.RenameField(
            model_name="technique",
            old_name="difficty_level",
            new_name="difficulty_level",
        ),
        migrations.AlterField(
            model_name="technique",
            name="steps",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
