# Generated by Django 5.1.5 on 2025-02-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0003_rename_difficty_level_combo_difficulty_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combo",
            name="target",
            field=models.ManyToManyField(related_name="combos", to="tutorials.target"),
        ),
        migrations.AlterField(
            model_name="combo",
            name="technique",
            field=models.ManyToManyField(
                related_name="combos", to="tutorials.technique"
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcategories",
                to="tutorials.category",
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="techniques",
                to="tutorials.subcategory",
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="target",
            field=models.ManyToManyField(
                related_name="techniques", to="tutorials.target"
            ),
        ),
    ]
