# Generated by Django 5.1.6 on 2025-02-19 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorials", "0004_alter_combo_target_alter_combo_technique_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videotutorial",
            name="url",
        ),
        migrations.AddField(
            model_name="videotutorial",
            name="iframe",
            field=models.TextField(default="Iframe here"),
        ),
        migrations.AlterField(
            model_name="videotutorial",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/images/tutorials"
            ),
        ),
        migrations.AlterField(
            model_name="videotutorial",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_tutorials",
                to="tutorials.subcategory",
            ),
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(unique=True)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("youtube_url", models.URLField()),
                ("twitter_url", models.URLField()),
                ("personal_url", models.URLField()),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
